<?php

return [
	'bounce'            => esc_html__( 'Bounce', 'starter-kit' ),
	'pulse'             => esc_html__( 'Pulse', 'starter-kit' ),
	'tada'              => esc_html__( 'Tada', 'starter-kit' ),
	'wobble'            => esc_html__( 'Wobble', 'starter-kit' ),
	'jello'             => esc_html__( 'Jello', 'starter-kit' ),
	'bounceIn'          => esc_html__( 'Bounce In', 'starter-kit' ),
	'bounceInDown'      => esc_html__( 'Bounce In Down', 'starter-kit' ),
	'bounceInLeft'      => esc_html__( 'Bounce In Left', 'starter-kit' ),
	'bounceInRight'     => esc_html__( 'Bounce In Right', 'starter-kit' ),
	'bounceInUp'        => esc_html__( 'Bounce In Up', 'starter-kit' ),
	'fadeIn'            => esc_html__( 'Fade In', 'starter-kit' ),
	'fadeInDown'        => esc_html__( 'Fade In Down', 'starter-kit' ),
	'fadeInDownBig'     => esc_html__( 'Fade In Down Big', 'starter-kit' ),
	'fadeInLeft'        => esc_html__( 'Fade In Left', 'starter-kit' ),
	'fadeInLeftBig'     => esc_html__( 'Fade In Left Big', 'starter-kit' ),
	'fadeInRight'       => esc_html__( 'Fade In Right', 'starter-kit' ),
	'fadeInRightBig'    => esc_html__( 'Fade In Right Big', 'starter-kit' ),
	'fadeInUp'          => esc_html__( 'Fade In Up', 'starter-kit' ),
	'fadeInUpBig'       => esc_html__( 'Fade In Up Big', 'starter-kit' ),
	'flip'              => esc_html__( 'Flip', 'starter-kit' ),
	'flipInX'           => esc_html__( 'Flip in X', 'starter-kit' ),
	'flipInY'           => esc_html__( 'Flip in Y', 'starter-kit' ),
	'flipOutX'          => esc_html__( 'Flip out X', 'starter-kit' ),
	'flipOutY'          => esc_html__( 'Flip out Y', 'starter-kit' ),
	'lightSpeedIn'      => esc_html__( 'Light Speed In', 'starter-kit' ),
	'rotateIn'          => esc_html__( 'Rotate In', 'starter-kit' ),
	'rotateInDownLeft'  => esc_html__( 'Rotate In Down Left', 'starter-kit' ),
	'rotateInDownRight' => esc_html__( 'Rotate In Down Right', 'starter-kit' ),
	'rotateInUpLeft'    => esc_html__( 'Rotate In Up Left', 'starter-kit' ),
	'rotateInUpRight'   => esc_html__( 'Rotate In Up Right', 'starter-kit' ),
	'slideInUp'         => esc_html__( 'Slide In Up', 'starter-kit' ),
	'slideInDown'       => esc_html__( 'Slide In Down', 'starter-kit' ),
	'slideInLeft'       => esc_html__( 'Slide In Left', 'starter-kit' ),
	'slideInRight'      => esc_html__( 'Slide In Right', 'starter-kit' ),
	'zoomIn'            => esc_html__( 'Zoom In', 'starter-kit' ),
	'zoomInDown'        => esc_html__( 'Zoom In Down', 'starter-kit' ),
	'zoomInLeft'        => esc_html__( 'Zoom In Left', 'starter-kit' ),
	'zoomInRight'       => esc_html__( 'Zoom In Right', 'starter-kit' ),
	'zoomInUp'          => esc_html__( 'Zoom In Up', 'starter-kit' ),
];
