<?php

namespace StarterKit\Repository;

defined('ABSPATH') || exit;

/**
 * Repository for Country directory objects
 *
 * @package    Starter Kit
 */
class CountryRepository extends AbstractWpPostRepository
{

    public static function getPostTypeID(): string
    {
        // Country is not post type
        return '';
    }

    /**
     * Get countries array
     *
     * @return array
     */
    public static function getCountries(): array
    {
        // Countries array in UN with population more than 1 million
        return [
            'af' => __('Afghanistan', 'starter-kit'),
            'al' => __('Albania', 'starter-kit'),
            'dz' => __('Algeria', 'starter-kit'),
            'ad' => __('Andorra', 'starter-kit'),
            'ao' => __('Angola', 'starter-kit'),
            'ag' => __('Antigua and Barbuda', 'starter-kit'),
            'ar' => __('Argentina', 'starter-kit'),
            'am' => __('Armenia', 'starter-kit'),
            'au' => __('Australia', 'starter-kit'),
            'at' => __('Austria', 'starter-kit'),
            'az' => __('Azerbaijan', 'starter-kit'),
            'bs' => __('Bahamas', 'starter-kit'),
            'bh' => __('Bahrain', 'starter-kit'),
            'bd' => __('Bangladesh', 'starter-kit'),
            'bb' => __('Barbados', 'starter-kit'),
            'by' => __('Belarus', 'starter-kit'),
            'be' => __('Belgium', 'starter-kit'),
            'bz' => __('Belize', 'starter-kit'),
            'bj' => __('Benin', 'starter-kit'),
            'bm' => __('Bermuda', 'starter-kit'),
            'bt' => __('Bhutan', 'starter-kit'),
            'bo' => __('Bolivia', 'starter-kit'),
            'ba' => __('Bosnia and Herzegovina', 'starter-kit'),
            'bw' => __('Botswana', 'starter-kit'),
            'br' => __('Brazil', 'starter-kit'),
            'bn' => __('Brunei', 'starter-kit'),
            'bg' => __('Bulgaria', 'starter-kit'),
            'bf' => __('Burkina Faso', 'starter-kit'),
            'bi' => __('Burundi', 'starter-kit'),
            'kh' => __('Cambodia', 'starter-kit'),
            'cm' => __('Cameroon', 'starter-kit'),
            'ca' => __('Canada', 'starter-kit'),
            'cv' => __('Cape Verde', 'starter-kit'),
            'ky' => __('Cayman Islands', 'starter-kit'),
            'cf' => __('Central African Republic', 'starter-kit'),
            'td' => __('Chad', 'starter-kit'),
            'cl' => __('Chile', 'starter-kit'),
            'cn' => __('China', 'starter-kit'),
            'co' => __('Colombia', 'starter-kit'),
            'km' => __('Comoros', 'starter-kit'),
            'cg' => __('Congo', 'starter-kit'),
            'cd' => __('Congo, Democratic Republic', 'starter-kit'),
            'ck' => __('Cook Islands', 'starter-kit'),
            'cr' => __('Costa Rica', 'starter-kit'),
            'ci' => __('Cote d\'Ivoire', 'starter-kit'),
            'hr' => __('Croatia', 'starter-kit'),
            'cu' => __('Cuba', 'starter-kit'),
            'cw' => __('Curaçao', 'starter-kit'),
            'cy' => __('Cyprus', 'starter-kit'),
            'cz' => __('Czech Republic', 'starter-kit'),
            'dk' => __('Denmark', 'starter-kit'),
            'dj' => __('Djibouti', 'starter-kit'),
            'dm' => __('Dominica', 'starter-kit'),
            'do' => __('Dominican Republic', 'starter-kit'),
            'ec' => __('Ecuador', 'starter-kit'),
            'eg' => __('Egypt', 'starter-kit'),
            'sv' => __('El Salvador', 'starter-kit'),
            'gq' => __('Equatorial Guinea', 'starter-kit'),
            'er' => __('Eritrea', 'starter-kit'),
            'ee' => __('Estonia', 'starter-kit'),
            'et' => __('Ethiopia', 'starter-kit'),
            'fk' => __('Falkland Islands', 'starter-kit'),
            'fo' => __('Faroe Islands', 'starter-kit'),
            'fj' => __('Fiji', 'starter-kit'),
            'fi' => __('Finland', 'starter-kit'),
            'fr' => __('France', 'starter-kit'),
            'gf' => __('French Guiana', 'starter-kit'),
            'pf' => __('French Polynesia', 'starter-kit'),
            'ga' => __('Gabon', 'starter-kit'),
            'gm' => __('Gambia, The', 'starter-kit'),
            'ge' => __('Georgia', 'starter-kit'),
            'de' => __('Germany', 'starter-kit'),
            'gh' => __('Ghana', 'starter-kit'),
            'gi' => __('Gibraltar', 'starter-kit'),
            'gr' => __('Greece', 'starter-kit'),
            'gl' => __('Greenland', 'starter-kit'),
            'gd' => __('Grenada', 'starter-kit'),
            'gp' => __('Guadeloupe', 'starter-kit'),
            'gu' => __('Guam', 'starter-kit'),
            'gt' => __('Guatemala', 'starter-kit'),
            'gg' => __('Guernsey', 'starter-kit'),
            'gn' => __('Guinea', 'starter-kit'),
            'gw' => __('Guinea-Bissau', 'starter-kit'),
            'gy' => __('Guyana', 'starter-kit'),
            'ht' => __('Haiti', 'starter-kit'),
            'va' => __('Holy See', 'starter-kit'),
            'hn' => __('Honduras', 'starter-kit'),
            'hk' => __('Hong Kong', 'starter-kit'),
            'hu' => __('Hungary', 'starter-kit'),
            'is' => __('Iceland', 'starter-kit'),
            'in' => __('India', 'starter-kit'),
            'id' => __('Indonesia', 'starter-kit'),
            'ir' => __('Iran, Islamic Republic of', 'starter-kit'),
            'iq' => __('Iraq', 'starter-kit'),
            'ie' => __('Ireland', 'starter-kit'),
            'im' => __('Isle of Man', 'starter-kit'),
            'il' => __('Israel', 'starter-kit'),
            'it' => __('Italy', 'starter-kit'),
            'jm' => __('Jamaica', 'starter-kit'),
            'jp' => __('Japan', 'starter-kit'),
            'je' => __('Jersey', 'starter-kit'),
            'jo' => __('Jordan', 'starter-kit'),
            'kz' => __('Kazakhstan', 'starter-kit'),
            'ke' => __('Kenya', 'starter-kit'),
            'ki' => __('Kiribati', 'starter-kit'),
            'kw' => __('Kuwait', 'starter-kit'),
            'kg' => __('Kyrgyzstan', 'starter-kit'),
            'la' => __('Laos', 'starter-kit'),
            'lv' => __('Latvia', 'starter-kit'),
            'lb' => __('Lebanon', 'starter-kit'),
            'ls' => __('Lesotho', 'starter-kit'),
            'lr' => __('Liberia', 'starter-kit'),
            'ly' => __('Libya', 'starter-kit'),
            'li' => __('Liechtenstein', 'starter-kit'),
            'lt' => __('Lithuania', 'starter-kit'),
            'lu' => __('Luxembourg', 'starter-kit'),
            'mo' => __('Macao', 'starter-kit'),
            'mk' => __('Macedonia', 'starter-kit'),
            'mg' => __('Madagascar', 'starter-kit'),
            'mw' => __('Malawi', 'starter-kit'),
            'my' => __('Malaysia', 'starter-kit'),
            'mv' => __('Maldives', 'starter-kit'),
            'ml' => __('Mali', 'starter-kit'),
            'mt' => __('Malta', 'starter-kit'),
            'mq' => __('Martinique', 'starter-kit'),
            'mr' => __('Mauritania', 'starter-kit'),
            'mu' => __('Mauritius', 'starter-kit'),
            'yt' => __('Mayotte', 'starter-kit'),
            'mx' => __('Mexico', 'starter-kit'),
            'md' => __('Moldova', 'starter-kit'),
            'mc' => __('Monaco', 'starter-kit'),
            'mn' => __('Mongolia', 'starter-kit'),
            'me' => __('Montenegro', 'starter-kit'),
            'ms' => __('Montserrat', 'starter-kit'),
            'ma' => __('Morocco', 'starter-kit'),
            'mz' => __('Mozambique', 'starter-kit'),
            'mm' => __('Myanmar', 'starter-kit'),
            'na' => __('Namibia', 'starter-kit'),
            'nr' => __('Nauru', 'starter-kit'),
            'np' => __('Nepal', 'starter-kit'),
            'nl' => __('Netherlands', 'starter-kit'),
            'nc' => __('New Caledonia', 'starter-kit'),
            'nz' => __('New Zealand', 'starter-kit'),
            'ni' => __('Nicaragua', 'starter-kit'),
            'ne' => __('Niger', 'starter-kit'),
            'ng' => __('Nigeria', 'starter-kit'),
            'nu' => __('Niue', 'starter-kit'),
            'nf' => __('Norfolk Island', 'starter-kit'),
            'kp' => __('North Korea', 'starter-kit'),
            'no' => __('Norway', 'starter-kit'),
            'om' => __('Oman', 'starter-kit'),
            'pk' => __('Pakistan', 'starter-kit'),
            'pw' => __('Palau', 'starter-kit'),
            'pa' => __('Panama', 'starter-kit'),
            'pg' => __('Papua New Guinea', 'starter-kit'),
            'py' => __('Paraguay', 'starter-kit'),
            'pe' => __('Peru', 'starter-kit'),
            'ph' => __('Philippines', 'starter-kit'),
            'pn' => __('Pitcairn Islands', 'starter-kit'),
            'pl' => __('Poland', 'starter-kit'),
            'pt' => __('Portugal', 'starter-kit'),
            'pr' => __('Puerto Rico', 'starter-kit'),
            'qa' => __('Qatar', 'starter-kit'),
            're' => __('Reunion', 'starter-kit'),
            'ro' => __('Romania', 'starter-kit'),
            'ru' => __('Russia', 'starter-kit'),
            'rw' => __('Rwanda', 'starter-kit'),
            'sm' => __('San Marino', 'starter-kit'),
            'sa' => __('Saudi Arabia', 'starter-kit'),
            'sn' => __('Senegal', 'starter-kit'),
            'rs' => __('Serbia', 'starter-kit'),
            'sc' => __('Seychelles', 'starter-kit'),
            'sl' => __('Sierra Leone', 'starter-kit'),
            'sg' => __('Singapore', 'starter-kit'),
            'sk' => __('Slovakia', 'starter-kit'),
            'si' => __('Slovenia', 'starter-kit'),
            'sb' => __('Solomon Islands', 'starter-kit'),
            'so' => __('Somalia', 'starter-kit'),
            'za' => __('South Africa', 'starter-kit'),
            'kr' => __('South Korea', 'starter-kit'),
            'ss' => __('South Sudan', 'starter-kit'),
            'es' => __('Spain', 'starter-kit'),
            'lk' => __('Sri Lanka', 'starter-kit'),
            'sd' => __('Sudan', 'starter-kit'),
            'sr' => __('Suriname', 'starter-kit'),
            'sz' => __('Swaziland', 'starter-kit'),
            'se' => __('Sweden', 'starter-kit'),
            'ch' => __('Switzerland', 'starter-kit'),
            'sy' => __('Syria', 'starter-kit'),
            'tw' => __('Taiwan', 'starter-kit'),
            'tj' => __('Tajikistan', 'starter-kit'),
            'tz' => __('Tanzania', 'starter-kit'),
            'th' => __('Thailand', 'starter-kit'),
            'tl' => __('Timor-Leste', 'starter-kit'),
            'tg' => __('Togo', 'starter-kit'),
            'tk' => __('Tokelau', 'starter-kit'),
            'to' => __('Tonga', 'starter-kit'),
            'tt' => __('Trinidad and Tobago', 'starter-kit'),
            'tn' => __('Tunisia', 'starter-kit'),
            'tr' => __('Turkey', 'starter-kit'),
            'tm' => __('Turkmenistan', 'starter-kit'),
            'tv' => __('Tuvalu', 'starter-kit'),
            'ug' => __('Uganda', 'starter-kit'),
            'ua' => __('Ukraine', 'starter-kit'),
            'ae' => __('United Arab Emirates', 'starter-kit'),
            'gb' => __('United Kingdom', 'starter-kit'),
            'us' => __('United States', 'starter-kit'),
            'uy' => __('Uruguay', 'starter-kit'),
            'uz' => __('Uzbekistan', 'starter-kit'),
            'vu' => __('Vanuatu', 'starter-kit'),
            've' => __('Venezuela', 'starter-kit'),
            'vn' => __('Vietnam', 'starter-kit'),
            'vg' => __('Virgin Islands', 'starter-kit'),
            'wf' => __('Wallis and Futuna', 'starter-kit'),
            'eh' => __('Western Sahara', 'starter-kit'),
            'ye' => __('Yemen', 'starter-kit'),
            'zm' => __('Zambia', 'starter-kit'),
            'zw' => __('Zimbabwe', 'starter-kit'),
        ];
    }

}
